export type PublicSitter = {
  id: string
  name: string
  location: string
  rating: number
  reviews: number
  tags: string[]
  badge: string
  badgeTone: 'orange' | 'green'
  image: string
  hourlyRate: number
  yearsExperience: number
  about: string
  availability: string[]
}

export type PublicHouseSit = {
  id: string
  title: string
  location: string
  dateRange: string
  type: string
  beds: string
  baths: string
  pets: string
  rating: number
  applications: number
  badge: string
  daysLeft: string
  image: string
  gallery: string[]
  homeownerName: string
  homeownerAvatar: string
  statusLabel: string
  description: string
  amenities: string[]
  responsibilities: string[]
  compensation: string
}

export const PUBLIC_SITTERS: PublicSitter[] = [
  {
    id: 'hol',
    name: 'Hollie Offord',
    location: 'No Location Found',
    rating: 0,
    reviews: 0,
    tags: ['Dog Walking', 'Garden Maintenance'],
    badge: 'Premium Verified',
    badgeTone: 'orange',
    image: 'https://images.unsplash.com/photo-1616683693504-3ea7e9ad6fec?auto=format&fit=crop&w=900&q=80',
    hourlyRate: 0,
    yearsExperience: 3,
    about: 'Reliable and calm house sitter focused on keeping homes secure, tidy, and cared for while homeowners are away.',
    availability: ['Weekdays'],
  },
  {
    id: 'faye-walker',
    name: 'Faye Walker',
    location: 'Lower Dicker, Hailsham BN27, UK',
    rating: 0,
    reviews: 0,
    tags: ['Dog Walking', 'Property Care & Security', 'Cleaning'],
    badge: 'Premium Verified',
    badgeTone: 'orange',
    image: 'https://images.unsplash.com/photo-1488426862026-3ee34a7d66df?auto=format&fit=crop&w=900&q=80',
    hourlyRate: 24,
    yearsExperience: 4,
    about: 'Experienced house sitter with strong routines for pet care, cleaning, and daily home checks.',
    availability: ['Weekdays', 'Weekends'],
  },
  {
    id: 'bee',
    name: 'Bee',
    location: 'Sydney NSW, Australia',
    rating: 5,
    reviews: 1,
    tags: ['Pet Care', 'Dog Walking', 'Cat Care'],
    badge: 'Premium Verified',
    badgeTone: 'orange',
    image: 'https://images.unsplash.com/photo-1521572267360-ee0c2909d518?auto=format&fit=crop&w=900&q=80',
    hourlyRate: 28,
    yearsExperience: 5,
    about: 'Pet-first house sitter who ensures routines stay consistent for both animals and property.',
    availability: ['Flexible'],
  },
  {
    id: 'zc',
    name: 'ZC',
    location: 'Cotswolds, UK',
    rating: 5,
    reviews: 1,
    tags: ['Dog Walking', 'Plant Care', 'Garden Maintenance'],
    badge: 'Premium Verified',
    badgeTone: 'orange',
    image: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=900&q=80',
    hourlyRate: 26,
    yearsExperience: 4,
    about: 'Hands-on sitter with a focus on outdoor maintenance, pet wellbeing, and tidy home standards.',
    availability: ['Weekdays'],
  },
  {
    id: 'liv-k-1',
    name: 'Liv K',
    location: 'Crewe-by-Farndon, Chester CH3 6PH, UK',
    rating: 4,
    reviews: 1,
    tags: ['Dog Walking', 'Cooking', 'Cleaning', 'Driving'],
    badge: 'Premium Verified',
    badgeTone: 'orange',
    image: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?auto=format&fit=crop&w=900&q=80',
    hourlyRate: 23,
    yearsExperience: 4,
    about: 'Dependable sitter who handles pets, household tasks, and daily routines with consistency.',
    availability: ['Weekdays', 'Evenings'],
  },
  {
    id: 'mia',
    name: 'Mia',
    location: 'Carmel Valley, San Diego, CA, USA',
    rating: 3.5,
    reviews: 6,
    tags: ['Plant Care', 'Property Care & Security', 'First Aid'],
    badge: 'Premium Verified',
    badgeTone: 'orange',
    image: 'https://images.unsplash.com/photo-1521119989659-a83eee488004?auto=format&fit=crop&w=900&q=80',
    hourlyRate: 27,
    yearsExperience: 6,
    about: 'Security-conscious sitter with practical first-aid training and structured care routines.',
    availability: ['Flexible'],
  },
  {
    id: 'shez',
    name: 'Shez',
    location: 'No Location Found',
    rating: 3.3,
    reviews: 3,
    tags: ['Pool Maintenance', 'Property Care & Security'],
    badge: 'Verified',
    badgeTone: 'green',
    image: 'https://images.unsplash.com/photo-1507591064344-4c6ce005b128?auto=format&fit=crop&w=900&q=80',
    hourlyRate: 22,
    yearsExperience: 3,
    about: 'Practical sitter with strong attention to pool checks and general home safety.',
    availability: ['Weekdays'],
  },
  {
    id: 'olivia-martinez',
    name: 'Olivia Martinez',
    location: 'No Location Found',
    rating: 3.5,
    reviews: 2,
    tags: ['Cat Care', 'Cleaning', 'CPR Certified'],
    badge: 'Verified',
    badgeTone: 'green',
    image: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=900&q=80',
    hourlyRate: 21,
    yearsExperience: 2,
    about: 'Compassionate and detail-focused sitter with a calm approach and clean-home routines.',
    availability: ['Weekdays'],
  },
  {
    id: 'liv-k-2',
    name: 'Liv K',
    location: 'Davenham, UK',
    rating: 5,
    reviews: 1,
    tags: ['Pet Care', 'Dog Walking', 'Cooking', 'Cleaning'],
    badge: 'Verified',
    badgeTone: 'green',
    image: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=900&q=80',
    hourlyRate: 25,
    yearsExperience: 4,
    about: 'Versatile sitter trusted by repeat homeowners for day-to-day home and pet support.',
    availability: ['Weekdays', 'Weekends'],
  },
]

export const PUBLIC_HOUSE_SITS: PublicHouseSit[] = [
  {
    id: 'demo',
    title: 'Coastal Family Home in Brighton',
    location: 'Baroda, MI 49101, USA',
    dateRange: '13/05/2026 to 26/05/2026',
    type: 'Studio',
    beds: '2',
    baths: '1',
    pets: 'Hamster',
    rating: 0,
    applications: 0,
    badge: 'Urgent',
    daysLeft: '14 days',
    image: 'https://images.unsplash.com/photo-1516280440614-37939bbacd81?auto=format&fit=crop&w=1400&q=80',
    gallery: [
      'https://images.unsplash.com/photo-1516280440614-37939bbacd81?auto=format&fit=crop&w=1400&q=80',
      'https://images.unsplash.com/photo-1505693416388-ac5ce068fe85?auto=format&fit=crop&w=1400&q=80',
    ],
    homeownerName: 'Isabella Davis',
    homeownerAvatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?auto=format&fit=crop&w=300&q=80',
    statusLabel: 'Approved',
    description:
      'We are looking for a reliable and caring house sitter for our beautiful family home near the Brighton coastline. The property includes comfortable living spaces, fast Wi-Fi, and easy access to local shops and cafes. We also have one friendly pet that needs regular care. We want someone who can keep the home secure, water indoor plants, and maintain a calm daily routine while we travel.',
    amenities: ['Washer', 'Dryer'],
    responsibilities: ['Garden maintenance', 'Pool care'],
    compensation: 'Free accommodation',
  },
  {
    id: 'gravity-house',
    title: 'Gravity House',
    location: 'Mumbai, Maharashtra, India',
    dateRange: '12/05/2026 to 16/05/2026',
    type: 'House',
    beds: '3',
    baths: '6',
    pets: '2 pets',
    rating: 0,
    applications: 0,
    badge: 'Urgent',
    daysLeft: '4 days',
    image: 'https://images.unsplash.com/photo-1467269204594-9661b134dd2b?auto=format&fit=crop&w=1400&q=80',
    gallery: [
      'https://images.unsplash.com/photo-1467269204594-9661b134dd2b?auto=format&fit=crop&w=1400&q=80',
      'https://images.unsplash.com/photo-1600585154526-990dced4db0d?auto=format&fit=crop&w=1400&q=80',
    ],
    homeownerName: 'Aaron Patel',
    homeownerAvatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=300&q=80',
    statusLabel: 'Approved',
    description:
      'Spacious family home with pool and outdoor area. We need a sitter who can handle daily home checks and light pet care while we are away.',
    amenities: ['Wi-Fi', 'Parking'],
    responsibilities: ['Pet feeding', 'General house checks'],
    compensation: 'Free accommodation',
  },
  {
    id: 'beautiful-home',
    title: 'Beautiful Home',
    location: 'Ahmedabad, Gujarat, India',
    dateRange: '12/05/2026 to 14/05/2026',
    type: 'Apartment',
    beds: '3',
    baths: '5',
    pets: '1 pet',
    rating: 0,
    applications: 0,
    badge: 'Active',
    daysLeft: '2 days',
    image: 'https://images.unsplash.com/photo-1494526585095-c41746248156?auto=format&fit=crop&w=1400&q=80',
    gallery: [
      'https://images.unsplash.com/photo-1494526585095-c41746248156?auto=format&fit=crop&w=1400&q=80',
      'https://images.unsplash.com/photo-1484154218962-a197022b5858?auto=format&fit=crop&w=1400&q=80',
    ],
    homeownerName: 'Neha Shah',
    homeownerAvatar: 'https://images.unsplash.com/photo-1521119989659-a83eee488004?auto=format&fit=crop&w=300&q=80',
    statusLabel: 'Approved',
    description:
      'Modern apartment in a central area. We need someone reliable for a short sit with basic care instructions.',
    amenities: ['Air conditioning', 'Elevator'],
    responsibilities: ['Water plants', 'Secure property'],
    compensation: 'Free accommodation',
  },
  {
    id: 'sada',
    title: 'Sada',
    location: 'Suratgarh, Rajasthan 335804, India',
    dateRange: '08/05/2026 to 25/05/2026',
    type: 'Villa',
    beds: '2',
    baths: '1',
    pets: '0 pets',
    rating: 0,
    applications: 0,
    badge: 'Active',
    daysLeft: '17 days',
    image: 'https://images.unsplash.com/photo-1494526585095-c41746248156?auto=format&fit=crop&w=1400&q=80',
    gallery: [
      'https://images.unsplash.com/photo-1494526585095-c41746248156?auto=format&fit=crop&w=1400&q=80',
      'https://images.unsplash.com/photo-1572120360610-d971b9d7767c?auto=format&fit=crop&w=1400&q=80',
    ],
    homeownerName: 'Rohan Khanna',
    homeownerAvatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=300&q=80',
    statusLabel: 'Approved',
    description:
      'Quiet villa with secure neighborhood access and minimal maintenance needs.',
    amenities: ['Wi-Fi', 'Workspace'],
    responsibilities: ['General check-ins'],
    compensation: 'Free accommodation',
  },
  {
    id: 'test-house',
    title: 'Test House',
    location: 'London, UK',
    dateRange: '18/05/2026 to 25/05/2026',
    type: 'Apartment',
    beds: '4',
    baths: '3',
    pets: '1 pet',
    rating: 0,
    applications: 0,
    badge: 'Urgent',
    daysLeft: '7 days',
    image: 'https://images.unsplash.com/photo-1484154218962-a197022b5858?auto=format&fit=crop&w=1400&q=80',
    gallery: [
      'https://images.unsplash.com/photo-1484154218962-a197022b5858?auto=format&fit=crop&w=1400&q=80',
      'https://images.unsplash.com/photo-1605146769289-440113cc3d00?auto=format&fit=crop&w=1400&q=80',
    ],
    homeownerName: 'Olivia Reed',
    homeownerAvatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?auto=format&fit=crop&w=300&q=80',
    statusLabel: 'Approved',
    description:
      'Comfortable apartment sit with one friendly pet and clear routine instructions.',
    amenities: ['Wi-Fi', 'Washer'],
    responsibilities: ['Pet care', 'Home security'],
    compensation: 'Free accommodation',
  },
  {
    id: 'tested',
    title: 'Tested',
    location: 'Surat, Gujarat, India',
    dateRange: '05/05/2026 to 27/05/2026',
    type: 'Apartment',
    beds: '3',
    baths: '4',
    pets: '1 pet',
    rating: 0,
    applications: 0,
    badge: 'Urgent',
    daysLeft: '22 days',
    image: 'https://images.unsplash.com/photo-1605146769289-440113cc3d00?auto=format&fit=crop&w=1400&q=80',
    gallery: [
      'https://images.unsplash.com/photo-1605146769289-440113cc3d00?auto=format&fit=crop&w=1400&q=80',
      'https://images.unsplash.com/photo-1512918728675-ed5a9ecdebfd?auto=format&fit=crop&w=1400&q=80',
    ],
    homeownerName: 'Aanya Rao',
    homeownerAvatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=300&q=80',
    statusLabel: 'Approved',
    description:
      'Longer sit for a well-kept apartment with straightforward home routines.',
    amenities: ['Wi-Fi', 'Kitchen'],
    responsibilities: ['Pet feeding', 'Plant care'],
    compensation: 'Free accommodation',
  },
  {
    id: 'rustic-farmhouse',
    title: 'Rustic Farmhouse',
    location: 'Cotswold District, UK',
    dateRange: '06/05/2026 to 26/05/2026',
    type: 'Farmhouse',
    beds: '4',
    baths: '4',
    pets: '2 pets',
    rating: 4.9,
    applications: 1,
    badge: 'Active',
    daysLeft: '20 days',
    image: 'https://images.unsplash.com/photo-1512918728675-ed5a9ecdebfd?auto=format&fit=crop&w=1400&q=80',
    gallery: [
      'https://images.unsplash.com/photo-1512918728675-ed5a9ecdebfd?auto=format&fit=crop&w=1400&q=80',
      'https://images.unsplash.com/photo-1600585153490-76fb20a32601?auto=format&fit=crop&w=1400&q=80',
    ],
    homeownerName: 'Harry Collins',
    homeownerAvatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=300&q=80',
    statusLabel: 'Approved',
    description:
      'Peaceful farmhouse sit with two pets and a simple care routine near walking trails.',
    amenities: ['Parking', 'Garden'],
    responsibilities: ['Pet care', 'Garden checks'],
    compensation: 'Free accommodation',
  },
  {
    id: 'cozy-family-home',
    title: 'Cozy Family Home in Quiet Suburb',
    location: 'Austin, TX, USA',
    dateRange: '10/08/2026 to 20/08/2026',
    type: 'House',
    beds: '3',
    baths: '1',
    pets: '1 pet',
    rating: 4.8,
    applications: 2,
    badge: 'Urgent',
    daysLeft: '10 days',
    image: 'https://images.unsplash.com/photo-1564013799919-ab600027ffc6?auto=format&fit=crop&w=1400&q=80',
    gallery: [
      'https://images.unsplash.com/photo-1564013799919-ab600027ffc6?auto=format&fit=crop&w=1400&q=80',
      'https://images.unsplash.com/photo-1499793983690-e29da59ef1c2?auto=format&fit=crop&w=1400&q=80',
    ],
    homeownerName: 'Emily Johnson',
    homeownerAvatar: 'https://images.unsplash.com/photo-1521572267360-ee0c2909d518?auto=format&fit=crop&w=300&q=80',
    statusLabel: 'Approved',
    description:
      'Family home near parks and schools. We need a sitter comfortable with one pet and regular home routines.',
    amenities: ['Wi-Fi', 'Parking', 'Washer'],
    responsibilities: ['Pet care', 'Light cleaning'],
    compensation: 'Free accommodation',
  },
  {
    id: 'oceanfront-condo',
    title: 'Oceanfront Condo in Miami Beach',
    location: 'Miami, FL, USA',
    dateRange: '10/08/2026 to 30/08/2026',
    type: 'Apartment',
    beds: '3',
    baths: '2',
    pets: '0 pets',
    rating: 4.7,
    applications: 0,
    badge: 'Urgent',
    daysLeft: '19 days',
    image: 'https://images.unsplash.com/photo-1499793983690-e29da59ef1c2?auto=format&fit=crop&w=1400&q=80',
    gallery: [
      'https://images.unsplash.com/photo-1499793983690-e29da59ef1c2?auto=format&fit=crop&w=1400&q=80',
      'https://images.unsplash.com/photo-1505693416388-ac5ce068fe85?auto=format&fit=crop&w=1400&q=80',
    ],
    homeownerName: 'Mason Clarke',
    homeownerAvatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=300&q=80',
    statusLabel: 'Approved',
    description:
      'Oceanfront condo sit with no pets and minimal upkeep beyond security and basic checks.',
    amenities: ['Gym', 'Pool', 'Wi-Fi'],
    responsibilities: ['General check-ins'],
    compensation: 'Free accommodation',
  },
  {
    id: 'modern-family-home',
    title: 'Modern 3-Bedroom Family Home',
    location: 'United States',
    dateRange: '10/08/2026 to 20/08/2026',
    type: 'House',
    beds: '2',
    baths: '1',
    pets: '1 pet',
    rating: 4.6,
    applications: 2,
    badge: 'Active',
    daysLeft: '12 days',
    image: 'https://images.unsplash.com/photo-1600585154526-990dced4db0d?auto=format&fit=crop&w=1400&q=80',
    gallery: [
      'https://images.unsplash.com/photo-1600585154526-990dced4db0d?auto=format&fit=crop&w=1400&q=80',
      'https://images.unsplash.com/photo-1600585153490-76fb20a32601?auto=format&fit=crop&w=1400&q=80',
    ],
    homeownerName: 'Sophie Turner',
    homeownerAvatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=300&q=80',
    statusLabel: 'Approved',
    description:
      'Modern home sit with one pet and clear household instructions in a safe neighborhood.',
    amenities: ['Wi-Fi', 'Parking'],
    responsibilities: ['Pet care', 'Home checks'],
    compensation: 'Free accommodation',
  },
]
